language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 5.3

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - sudo apt-get install -y --force-yes php5-intl
  - composer self-update
  - composer install --dev

script: ./vendor/bin/phing
